server:
  port: 9094

spring:
  profiles:
    active: dev

  application:
    name: ORDER-SERVICE

  data:
   mongodb:
     uri: {DB_URL}
     host: {DB_HOST}
     port: {DB_PORT}
     database: {DB_NAME}
     repositories:
       type: AUTO

